### ISSUE TITLE
Identifying a list of questions to be clarified by customers and documenting them.

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#13]
Identify a list of questions to be clarified by customers. Create a wiki page and document them.

**Comment by supiket** [comment]
[Requirements Wiki Page](https://github.com/bounswe/2021SpringGroup2/wiki/Requirements)

**Comment by supiket** [comment]
[Questions for Customers Wiki Page](https://github.com/bounswe/2021SpringGroup2/wiki/Questions-for-Customers)

**Comment by berkaydoner** [comment]
I added some questions. I think we will have more questions while formulating the requirements, so I am not closing the issue yet.

**Comment by berkaydoner** [comment]
Necip and I added some questions about the topics we discussed in the meeting. It seems we don't have any more questions.
