### ISSUE TITLE
Revising the Project Requirements

### ISSUE THREAD

**Issue by Voursstrreds** [bounswe/2021SpringGroup2#130]
Some functional requirements are needed to be changed before working on it.

**Comment by ahmetnecipg** [comment]
Added "Notification" definition to the glossary.

**Comment by ahmetnecipg** [comment]
**Added:**
**1.1.3.11.** User should be registered in order to write comments under posts.<br>

**Comment by Voursstrreds** [comment]
I suggest a final review to the "User Requirement" work. The final text is

`1.1. User Requirements
    1.1.1. Sign Up
        1.1.1.1. Users shall register to be a registered user.
        1.1.1.2. Users shall specify their email, password and username while registering.
        1.1.1.3. Users shall accept the terms and conditions document to register.
        1.1.1.4. Users shall fill personal information form while registering.
        1.1.1.5. Users should select their interests and skills to get suggestions from the system.
    1.1.2. Sign In
        1.1.2.1. Registered users shall enter their email or username and password to sign in.
    1.1.3. Registered Users
        1.1.3.1. Registered users shall have a personal profile page.
        1.1.3.2. Registered users should edit their profile page according to their interests and skills.
        1.1.3.3. Registered users shall not be blocked by the user to view a user's profile page.
        1.1.3.4. User should be registered in order to write comments under posts.
    1.1.4 Search
        1.1.4.1 Registered users shall use the search feature to find users or posts.
    1.1.5 Post
        1.1.5.1 Event Post
            1.1.5.1.1 Registered users shall enter the values of the event to create an event post.
            1.1.5.1.2 Event creators shall specify the type of sports events, manage location and type of sports events.
            1.1.5.1.3 Event creators shall select the participants among the applicants.
            1.1.5.1.4 Event creators shall report game results along with analytics.
            1.1.5.1.5 Users shall indicate the type of sport and location in order to filter events.
            1.1.5.1.6 Registered users shall specify their interests and skills to be able to get event recommendations. 
        1.1.5.2 Equipment Post
            1.1.5.2.1 Registered users shall enter the values of the equipment to create an equipment post.
            1.1.5.2.2 Registered users shall select the proper post and enter the contents of a comment to enter a comment.
            1.1.5.2.3 Users shall indicate the type of sport and location in order to filter equipments    
    1.1.6 Notification
        1.1.6.1 Registered users shall select which notifications that they will see.
        1.1.6.2 Registered users shall enable or disable all or a subset of notifications.
`

@supiket @ibrahimbayat Request is needed.

**Comment by supiket** [comment]
User requirements "1.1.1.5. Users should select their interests and skills to get suggestions from the system." and "1.1.3.2. Registered users should edit their profile page according to their interests and skills." are very similar and 1.1.3.2 is not required. I suggest removing 1.1.3.2.

**Comment by Voursstrreds** [comment]
I inspected the recommendations.

> User requirements "1.1.1.5. Users should select their interests and skills to get suggestions from the system." and "1.1.3.2. Registered users should edit their profile page according to their interests and skills." are very similar and 1.1.3.2 is not required. I suggest removing 1.1.3.2.

I deleted the 1.1.3.2.

> What is the difference between 1.5.1.1 and 1.5.1.2? Shouldn't the phrase "registered users' in 1.5.1.1 be "event creators", since the registered users that create events are called "event creators"? Edit: Now that I read again, I think in order to refer to a registered user as "event creator", 1.5.1.1 should not be removed. Feel free to discuss this topic.

The first one determines the necessity, the second one determines how to do specifically. Therefore two is better.

> We may consider adding:
> 
> > 1.1.5.2.4 Registered users shall specify their interests and skills to be able to get equipment recommendations.
> 
> Anyone reading this comment is proposition is welcome to comment on this topic.

Added.

The final text is:

```
1.1. User Requirements
    1.1.1. Sign Up
        1.1.1.1. Users shall register to be a registered user.
        1.1.1.2. Users shall specify their email, password and username while registering.
        1.1.1.3. Users shall accept the terms and conditions document to register.
        1.1.1.4. Users shall fill personal information form while registering.
        1.1.1.5. Users should select their interests and skills to get suggestions from the system.
    1.1.2. Sign In
        1.1.2.1. Registered users shall enter their email or username and password to sign in.
    1.1.3. Registered Users
        1.1.3.1. Registered users shall have a personal profile page.
        1.1.3.2. Registered users shall not be blocked by the user to view a user's profile page.
        1.1.3.3. User should be registered in order to write comments under posts.
    1.1.4 Search
        1.1.4.1 Registered users shall use the search feature to find users or posts.
    1.1.5 Post
        1.1.5.1 Event Post
            1.1.5.1.1 Registered users shall enter the values of the event to create an event post.
            1.1.5.1.2 Event creators shall specify the type of sports events, manage location and type of sports events.
            1.1.5.1.3 Event creators shall select the participants among the applicants.
            1.1.5.1.4 Event creators shall report game results along with analytics.
            1.1.5.1.5 Users shall indicate the type of sport and location in order to filter events.
            1.1.5.1.6 Registered users shall specify their interests and skills to be able to get event recommendations. 
        1.1.5.2 Equipment Post
            1.1.5.2.1 Registered users shall enter the values of the equipment to create an equipment post.
            1.1.5.2.2 Registered users shall select the proper post and enter the contents of a comment to enter a comment.
            1.1.5.2.3 Users shall indicate the type of sport and location in order to filter equipments
            1.1.5.2.4 Registered users shall specify their interests and skills to be able to get equipment recommendations.  
    1.1.6 Notification
        1.1.6.1 Registered users shall select which notifications that they will see.
        1.1.6.2 Registered users shall enable or disable all or a subset of notifications.
```
User requirements will be changed according to this.

**Comment by ibrahimbayat** [comment]
With given recommendations, user requirements can be used in this way. I think it is good and detailed.
