### ISSUE TITLE
Reviewing/Revising Scenario #3: User applies to an event to be a player&spectator

### ISSUE THREAD

**Issue by berkaydoner** [bounswe/2021SpringGroup2#131]
Since we are changing some of the requirements, I think it is necessary to check the previous scenarios&mockups as well. 
I will review my mockup and change it if necessary. I might also ask for review from others. I don't think I will need revisions for story, persona and goals parts since we did not change the main structure of our project. This scenario can be accessed from [here](https://github.com/bounswe/2021SpringGroup2/wiki/Scenario-%233:-User-applies-to-an-event-to-be-a-player&spectator).

- [x] Acceptance Criteria
- [x] Mockups

**Comment by berkaydoner** [comment]
I checked the acceptance criteria and noticed some revisions. I removed GUI requirements since we decided to remove them from our requirements. Also, I added the new requirements related to user profiles and notifications to acceptance criteria:
* (**1.2.4.3.**) User profile shall display personal information, skills, badges, followers, followings and post history.
* (**1.2.10.1.**) System shall notify users when their player/spectator applications are approved/rejected.

I think these changes are enough for acceptance criteria and I will check for any further changes if we continue changing our project requirements.

**Comment by berkaydoner** [comment]
I went over my mockups and could not find any need for revision. I think my mockups match our project requirements. Just in case I have not noticed some mistakes, @ahmetnecipg could you also review my mockups?

**Comment by ahmetnecipg** [comment]
Mockups are still fine since we did not exclude any features we explore in our mockups. They do a good job at demonstrating how specific scenarios are going to unfold in our website and mobile application. We can change the colors and overall look a bit for our actual project but no need to change the mockups.
