### ISSUE TITLE
[Android] Navigation Bar Icons

### ISSUE THREAD

**Issue by omerarslnn** [bounswe/2021SpringGroup2#148]
Custom icons for home and profile tabs of bottom navigation bar should be generated.

**Comment by ahmetnecipg** [comment]
Custom icons  for home and profile are added to the bottom navigation bar. Selector is not working and although it's not a necessity, it can be improved if we can find spare time. [The commit](https://github.com/bounswe/2021SpringGroup2/commit/c1b1dffe7622f04c04344be445298b13fb0d2702)
