### ISSUE TITLE
Merging React frontend with Django backend

### ISSUE THREAD

**Issue by ege-kaya** [bounswe/2021SpringGroup2#173]
We need to merge the backend and frontend make sure they are working together.

**Comment by CenekSanzak** [comment]
We created an app named react on the django project and set its route schema. I moved our frontend project to there so that we can serve our frontend app within the backend app. We set up template html files and a structure for static bundle.js to serve it in the django.

**Comment by CenekSanzak** [comment]
I created an app in the django project named frontend. Our frontend project copies its built files to this app's static folder and django serves that static files. After this process it is accesible by docker image. We will have both our frontend and backend projects running on the server at the same machine and port. I tested it and it works. I created a pull request #208

**Comment by CenekSanzak** [comment]
It is reiewed and merged. It is working well.
