### ISSUE TITLE
Identifying non-functional requirements and documenting them.

### ISSUE THREAD

**Issue by supiket** [bounswe/2021SpringGroup2#18]
Research and document to [Requirements Wiki Page](https://github.com/bounswe/2021SpringGroup2/wiki/Requirements).

**Comment by berkaydoner** [comment]
I have prepared some requirements, however, it would be better if we discussed them together before closing the issue. Because some requirements include details about the implementation.

**Comment by berkaydoner** [comment]
I have made the necessary changes we talked about in the meeting.
