### ISSUE TITLE
Writing documentation for APIs

### ISSUE THREAD

**Issue by ibrahimbayat** [bounswe/2021SpringGroup2#196]
We need to write a documentation page for our APIs. It should specify the type of HTTP response, example response and failure values, parameters, paths and functionality of the APIs.

**Comment by ege-kaya** [comment]
I wrote the API documentation for the endpoints that I coded: register, login, reset password, get user profile

**Comment by ibrahimbayat** [comment]
I wrote documentation for get event by id , get all events, and posting new events functions which are written by me. I specified the type of HTTP response, example response and failure values, parameters, paths and functionalities of the APIs. You can see the documentation page from [here](https://github.com/bounswe/2021SpringGroup2/wiki/Rebound-API-documentation).

**Comment by ege-kaya** [comment]
The current situation is as follows: we have the API for comments & answers, block&follow, equipments, events, badges and user&profiles.
