### ISSUE TITLE
Uploading the customer meeting notes

### ISSUE THREAD

**Issue by berkaydoner** [bounswe/2021SpringGroup2#20]
We should document the topics we discussed during our meeting with the customer.  The notes should be in Q&A format.

**Comment by uskudarli** [comment]
Q&A is okay, but will also be good to summarize conclusions and action plans (as usual)

**Comment by berkaydoner** [comment]
I have added more questions&answers and also listed some conclusions and actions to be taken. I think we can close this issue now. Any future meetings with our customer should be handled in a separate issue.
