### ISSUE TITLE
Contribute to the Group Milestone 1 Report

### ISSUE THREAD

**Issue by ege-kaya** [bounswe/2021SpringGroup2#201]
We need to prepare the Group Milestone 1 Report complying to the outline given on the Moodle submission page.

**Comment by berkaydoner** [comment]
I have wrote the executive summary of the frontend part and the evaluation of the status of deliverables. I also copied our requirements to the report and highlighted the addressed requirements in this milestone with colors and comments, as discussed in #199. I also wrote the summary of the work I have done and included the images of the frontend pages I implemented.

**Comment by ahmetnecipg** [comment]
I have written the android part of the executive summary. I added the mockup scenarios to the report and fixed their acceptance criteria. I also wrote about Kotlin in "Evaluation of Tools" section.
