### ISSUE TITLE
[Backend] Comments and Answers API documentation

### ISSUE THREAD

**Issue by supiket** [bounswe/2021SpringGroup2#205]
We should write API documentation for commenting and answering.

**Comment by supiket** [comment]
Added API documentation for comments, using Activity Stream. Kudos to the Frontend team for their contributions to our discussions about the documentation!

The API documentation I added are: 

- Get comment to a post by id
- Get all comments to a post
- Create a comment to a post

**Comment by ibrahimbayat** [comment]
I contributed the comment and answer API documentation page with Get all answers to a comment and Create an answer to a comment APIs  with the help of my friends.

**Comment by supiket** [comment]
API documentation is ready.
