### ISSUE TITLE
[Backend] Comments and Answers API implementation

### ISSUE THREAD

**Issue by supiket** [bounswe/2021SpringGroup2#206]
We should implement comments and answers API, along with the models and API endpoints.

If necessary, we can split this issue into smaller parts during implementation.

**Comment by ibrahimbayat** [comment]
I have created the necessary comments app and created branch for that  [(commit)](https://github.com/bounswe/2021SpringGroup2/commit/477b2642f4bb9ba28c3014c3493e3c008a7c5bd7#diff-6eb30b27ca9e1a0f9ce50b60404e9b221db9becd5df36da444344177a0a60dfa). I have implemented get all comments of a post and create a comment for a post functionalities. I have also created models.py  for comments app and I tried to write these functionalities according to activity stream. [(commit)](https://github.com/bounswe/2021SpringGroup2/commit/c0d8ce77af2dee7fd30ee96e9b1a06507e1aba04#diff-6eb30b27ca9e1a0f9ce50b60404e9b221db9becd5df36da444344177a0a60dfa). I have tried to write some test functions for these functionalities  [(commit)](https://github.com/bounswe/2021SpringGroup2/commit/ff1be2713dc5db417cbcc5c7642faef1d8f8f5d3#diff-6eb30b27ca9e1a0f9ce50b60404e9b221db9becd5df36da444344177a0a60dfa).

**Comment by ibrahimbayat** [comment]
I have also implemented remaining parts. I have written get comment by id  [(commit)](https://github.com/bounswe/2021SpringGroup2/commit/354d9c9518e88c31e2239e571519ce7774784e9f),  get answers of a comment [(commit) ](https://github.com/bounswe/2021SpringGroup2/commit/d3c6c2500cc5de701ce5defa3b94c14ce6cb52a7) and create an answers for a comment [(commit)](https://github.com/bounswe/2021SpringGroup2/commit/361c058697bac3adf90df5105595ad7c87c94a0e) ,  according to activity stream and according to comment answer API documentation [(documentation)](https://github.com/bounswe/2021SpringGroup2/wiki/Comments-&-Answers-API-Documentation).
