### ISSUE TITLE
Creating Scenario 1 - Creating an Event

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#21]
- [x] Persona
- [x] Story
- [x] Pre-conditions
- [x] Goals
- [x] Acceptance Criteria
- [x] Web Mockup
- [x] Android Mockup

**Comment by ibrahimbayat** [comment]
Persona, story, pre-conditions, goals, acceptance criteria and web mockup is created.

**Comment by ibrahimbayat** [comment]
Android mockup is created. Mockup steps are included. User created events. After application of other players, event creator accepted them. After necessary acceptance, the teams are full.
