### ISSUE TITLE
[Frontend] Creating The Event Search Page And Components That Represent Events

### ISSUE THREAD

**Issue by CenekSanzak** [bounswe/2021SpringGroup2#219]
We should create a page for searching events by various metrics. Before adding the search functionality an event search page and components to show indicator about events should be created. In order it to be a divisible task, there should be a part for filter creator components and a structure that supports adding arbitrary number of filter objects and it should do the search using that objects.

**Comment by CenekSanzak** [comment]
I created a page for searching events. I added the `/search` route that displays that page. I added some initial filters and created a generic way of representing filters to make it possible to add more filters. I added initial values for all filter values.

**Comment by CenekSanzak** [comment]
I created a pull request for the initial state of the search page. It is merged and now anyone can open a branch and add more filters. I created the layout to create more filter objects.

**Comment by sseff** [comment]
I have created minimum date, maximum date, minimum creation date and maximum creation date filters for search page.
