### ISSUE TITLE
[Frontend] URLs in controllers should change

### ISSUE THREAD

**Issue by KeremZaman** [bounswe/2021SpringGroup2#221]
The controllers in frontend django app contain the URL of deployed application (e.g. https://github.com/bounswe/2021SpringGroup2/blob/development/frontend/src/Controllers/LoginController.js) . If someone wants to try the changes in backend through the UI in a local environment, the requests go to the deployed app and this might cause serious confusions.

We need to change the IP with localhost, so anyone can try the app in their local environment and we won't face any problem while deploying the app.

What do you think? @berkaydoner @CenekSanzak

**Comment by CenekSanzak** [comment]
I changed the ip adresses and made them use the localhost.
