### ISSUE TITLE
Creating Scenario 3 - User applies for an event as a player&spectator

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#23]
In this scenario, we can show how a user can apply to an event to be a player. It is also a good idea to show how users can apply to be spectators in this scenario since these two actions are very similar. Steps should clearly show the event page, application buttons and the result of the application.
- [x] Persona
- [x] Story
- [x] Pre-conditions
- [x] Goals
- [x] Acceptance Criteria
- [x] Web Mockup
- [x] Android Mockup

**Comment by berkaydoner** [comment]
I have added all the steps for both Web and Android mockups. I also showed the profile page of a user and the notification the users get when they are selected to an event in the mockups since they are related to the scenario.
