### ISSUE TITLE
Creating Scenario 5 - Discussion

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#25]
- [x] Persona
- [x] Story
- [x] Pre-conditions
- [x] Goals
- [x] Acceptance Criteria
- [x] Web Mockup
- [x] Android Mockup

**Comment by ahmetnecipg** [comment]
In this scenario a user uses the discussion section under an event.

**Comment by sseff** [comment]
![1web](https://user-images.githubusercontent.com/56451575/115163142-1e6bc680-a0b0-11eb-9334-bc795e65c537.PNG)
![2web](https://user-images.githubusercontent.com/56451575/115163146-1f045d00-a0b0-11eb-9ba5-c2e0983aa11c.PNG)
![3web](https://user-images.githubusercontent.com/56451575/115163147-1f9cf380-a0b0-11eb-992b-5a2ff7651ca6.PNG)
![4web](https://user-images.githubusercontent.com/56451575/115163150-1f9cf380-a0b0-11eb-9bfd-a21c3ad16827.PNG)
![1mob](https://user-images.githubusercontent.com/56451575/115163151-20358a00-a0b0-11eb-96f6-e89a8029acb5.PNG)
![2mob](https://user-images.githubusercontent.com/56451575/115163152-20358a00-a0b0-11eb-8ea4-e6cb7c3f38c4.PNG)
![3mob](https://user-images.githubusercontent.com/56451575/115163153-20ce2080-a0b0-11eb-8d39-850545e6aeee.PNG)
![4mob](https://user-images.githubusercontent.com/56451575/115163154-20ce2080-a0b0-11eb-9928-1d1d5eca27aa.PNG)

**Comment by CenekSanzak** [comment]
Scenario is completed, mockups are done on the miro board and uploaded to wiki as screenshots. Closing the issue.

**Comment by CenekSanzak** [comment]
![Screenshot from 2021-04-19 23-18-33](https://user-images.githubusercontent.com/36790615/115298101-b1b30380-a165-11eb-9582-3140f37efbb8.png)
![Screenshot from 2021-04-19 23-18-16](https://user-images.githubusercontent.com/36790615/115298105-b24b9a00-a165-11eb-8aaf-93ac1f418f1a.png)
