### ISSUE TITLE
[Frontend] Signup page is not loading

### ISSUE THREAD

**Issue by berkaydoner** [bounswe/2021SpringGroup2#252]
When I run the current version of our app from the development branch, the signup page is not loaded and it results in a blank page.

1. npm install 
2. npm run build
3. npm run start
4. Go to signup page from the button in the header
5. Page is blank and error message is printed on console:
```Uncaught TypeError: Cannot read properties of undefined (reading 'common')```

Page should not be blank as it is implemented and its code is in the branch.

![image](https://user-images.githubusercontent.com/52797716/145952370-7577dde8-3e70-4306-b7ec-586d8ccf11fa.png)

**Comment by CenekSanzak** [comment]
I created a branch for that bug report. Checked it out and tried. It works on me. Are you sure your npm packages are installed?
![image](https://user-images.githubusercontent.com/36790615/145957750-8270b060-70cc-4d53-9769-0cb98089ffef.png)

**Comment by berkaydoner** [comment]
Yes, this problem seems to be related to the package versions since this page is visible on the deployed server, which is using the current development branch. Thank you!
