### ISSUE TITLE
Creating the Class Diagram

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#27]
- [x] User
- [x] Post
- [x] Event Post
- [x] Equipment Post
- [x] Notification
- [x] Discussion
- [x] Discussion Comment
- [x] Search Handler
- [x] User Search
- [x] Event Search
- [x] Equipment Search

**Comment by ahmetnecipg** [comment]
I listed 10 entities we decided to create in our Class Diagram. Everyone has their own entities with the exception of "User" which is going to be a team task.

**Comment by ahmetnecipg** [comment]
I prepared the "Event Post" entity for our first draft of Class Diagram. It's highly likely that I'm going to need to make changes after the meeting with TA.

**Comment by CenekSanzak** [comment]
I filled the diagram for post and discussion classes.

**Comment by ahmetnecipg** [comment]
Overall the class diagram is good enough to work with therefore I'm closing this. It's currently on our miro board but it will be on our repository by the end of the week. 
Our miro board - https://miro.com/welcomeonboard/6XRG1UiscHo341fYJGhstfFrelEEPOAphdu6GoBz9FuiKL2H6ytDViE2iOKrGefT

**Comment by ege-kaya** [comment]
I filled the Equipment Post class of the diagram and made contributions to the Post class

**Comment by berkaydoner** [comment]
I have added the Notification Handler, Notification and User/Post Notification classes. I also contributed to the UserProfile class and its relationships between Privacy Option, Following and Blocking classes.

**Comment by KeremZaman** [comment]
I filled the diagram for post class, changed names of overloaded functions in search classes as recommended by TA and changed userID field in various classes to have correct data type.

**Comment by ibrahimbayat** [comment]
I filled the  class diagram for discussion comment.

**Comment by supiket** [comment]
I filled the diagram for user search class.

**Comment by supiket** [comment]
I added waiting() method to event application class.
