### ISSUE TITLE
[Backend] Bug Report: Fields in event instance should be relocated.

### ISSUE THREAD

**Issue by sseff** [bounswe/2021SpringGroup2#270]
"eventDate", "eventSport", "eventMinAge", "eventMaxAge", "eventMinSkillLevel", "eventMaxSkillLevel", "eventPlayerCapacity", "eventSpectatorCapacity", "eventApplicants", "eventPlayers" fields should be under "object" field in event instance.

**Comment by ege-kaya** [comment]
I have resolved the issue, it was due to a misplaced curly brace. Thanks for the heads up.
