### ISSUE TITLE
[Frontend] Bug report: The session variables are not working well

### ISSUE THREAD

**Issue by CenekSanzak** [bounswe/2021SpringGroup2#278]
The session variables (access and refresh token) are not working well. When the user refreshes or go back on the browser, they are lost. It can be solved by using the local storage.

**Comment by sseff** [comment]
Information is being locally storaged right now. Also when a user signs in, there will be a progile and logged out button. Also when a user logged out there will be a sign in button. These are working right now but there is need to refresh. It should be fixed.

**Comment by sseff** [comment]
I changed navigation part. There was not log out button. I have added it. Also when a user is logged in, s/he sees profile and log out buttons. Other way around. when a user logged out, s/he sees sign up button.

**Comment by sseff** [comment]
Also we are using localstorage right now.

**Comment by sseff** [comment]
We have merged these feature in the pull request #313 .
