### ISSUE TITLE
Creating Sequence Diagrams

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#28]
- [x] Search - Kerem Zaman
- [x] Create Event Post - Doğukan Akar
- [x] Create Equipment Post - Mehmet Saraçoğlu
- [x] Registration - Şefika Akman
- [x] Join Event as Player - Ahmet Necip Görgülü
- [x] Join Event as Spectator - İbrahim Bayat
- [x] Posting a Discussion Comment - Berkay Döner
- [x] Notification - Ege Can Kaya
- [x] Event Creator Selects from Appointees - Ömer Arslan

There were more diagrams added after we started out with these 9. You can see them all at : https://github.com/bounswe/2021SpringGroup2/wiki/Sequence-Diagrams

**Comment by ege-kaya** [comment]
I created 3 sequence diagrams involving notifications: 'user fetches notifications and reads one', 'user removes a notification by engaging with its content' and 'notification is sent by the action of a user'

**Comment by ahmetnecipg** [comment]
I created the sequence diagram regarding "Join Event as Player". After meeting with the TA I made some adjustments and turn it into it's final form.

**Comment by ibrahimbayat** [comment]
I created a sequence diagram for joining event as spectator.

**Comment by berkaydoner** [comment]
I have added 5 sequence diagrams:
* User posts a discussion comment on a post. 
* User answers a discussion comment.
* User gives a badge to another user.
* User follows a user.
* User blocks a user.

**Comment by KeremZaman** [comment]
I created sequence diagrams for searching user and searching equipment,

**Comment by CenekSanzak** [comment]
I created the sequence diagram for creating an event post, it includes post and event post classes.

**Comment by Voursstrreds** [comment]
I created the sequence diagram of creating an equipment post, and added it to the our wiki page.

**Comment by supiket** [comment]
Added alt boxes to diagrams that are missing alt boxes for success/failure messages.
