### ISSUE TITLE
[Android] Discussion section for Detailed Event Page

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#284]
Discussion section for Detailed Event Page needs to be added.

**Comment by Voursstrreds** [comment]
Main functionalities and basic fragments were created. They are working, but to see its full specifications, we need the data coming backend.

**Comment by ahmetnecipg** [comment]
With [this](https://github.com/bounswe/2021SpringGroup2/commit/0b56f024cad99f9c02d844520397f9b7acd9a7cb) commit discussion functionality for both event posts and equipment posts are implemented and working. This includes answer functionality as well.
