### ISSUE TITLE
[Backend] Fetching user information using user id

### ISSUE THREAD

**Issue by berkaydoner** [bounswe/2021SpringGroup2#294]
Since [Event Application API](https://github.com/bounswe/2021SpringGroup2/wiki/Event-API-Documentation#apply-to-an-event) uses user id's instead of usernames, we need to implement an API that returns the profile information of the user with given id. This information will be used to display usernames and possibly avatars in the applications page.

**Comment by ege-kaya** [comment]
I have implemented the feature
