### ISSUE TITLE
Create Wiki Pages for Github Repository Research

### ISSUE THREAD

**Issue by Voursstrreds** [bounswe/2021SpringGroup2#3]
- [x] KeremZaman
- [x] supiket
- [x] CenekSanzak
- [x] ege-kaya
- [x] berkaydoner
- [x] ibrahimbayat
- [x] sseff
- [x] Voursstrreds
- [x] ahmetnecipg
- [x] omerarslnn

**Comment by KeremZaman** [comment]
Each member must create seperate wiki pages for their Github repository research.

**Comment by supiket** [comment]
- [ ] KeremZaman
- [ ] supiket
- [ ] CenekSanzak
- [ ] ege-kaya
- [ ] berkaydoner
- [ ] ibrahimbayat
- [ ] sseff
- [ ] Voursstrreds
- [ ] ahmetnecipg
- [ ] omerarslnn
