### ISSUE TITLE
Create sequence diagram for "A user finds an event ten applies to it" scenario.

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#31]

**Comment by ahmetnecipg** [comment]
I created the diagram and showed it to our TA for feedback. According to the feedback I removed the part where the user was getting notified whether they're selected or not by the event creator. After getting the final draft approved by our TA I added the diagram to our page - https://github.com/bounswe/2021SpringGroup2/wiki/Sequence-Diagrams

**Comment by supiket** [comment]
Need to update the diagram to match the updated search functionality. (See the [related issue](https://github.com/bounswe/2021SpringGroup2/issues/36) for exact details of update.)

**Comment by supiket** [comment]
Implemented planned update.
