### ISSUE TITLE
Re-labeling the arrows in our Use Case Diagram

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#33]
We need to re-label the arrows in our Use Case Diagram according to the suggestions of our TA. This issue is about wrongly labeled <extend> arrows. We need to de-label them and reverse their directions.

**Comment by uskudarli** [comment]
@ahmetnecipg suggestion: You can specify the labeling criteria in your description. This will improve your issue. 
Also, need to make an assignment.

**Comment by ahmetnecipg** [comment]
I have removed the <extended> labels from arrows we have decided with our TA. After getting approved by our TA I'm closing this issue.

**Comment by supiket** [comment]
I have removed arrow labels from use cases including search actions.
