### ISSUE TITLE
[Frontend] Bug Report: Search page sport type filter

### ISSUE THREAD

**Issue by sseff** [bounswe/2021SpringGroup2#333]
Sport type filter of the search page does not work.

**Comment by CenekSanzak** [comment]
Fixed the bug on pull request #366

**Comment by sseff** [comment]
There was a sport type filter which was taking sport types and can not apply search. I have fixed that. 
Right now, users can select a sport type and according to this sport name, search event page shows related events.

**Comment by sseff** [comment]
Example Image of the Feature:
![sport type](https://user-images.githubusercontent.com/56451575/148576933-53e9a8c2-cb87-4dd8-900d-b2b3afb68212.png)
