### ISSUE TITLE
Create sequence diagram for "A user finds an event ten applies to it as spectator" scenario. 

### ISSUE THREAD

**Issue by ibrahimbayat** [bounswe/2021SpringGroup2#34]
I created the sequence diagram for " A user finds an event ten applies to it as spectator". I reorganized it according to feedbecks. 

![spectatorsequence](https://user-images.githubusercontent.com/56365449/117200616-f7213300-adeb-11eb-956d-80d26534a2b9.PNG)

 All sequence diagrams are here: https://github.com/bounswe/2021SpringGroup2/wiki/Sequence-Diagrams

**Comment by supiket** [comment]
Need to update the diagram to match the updated search functionality (See the [related issue](https://github.com/bounswe/2021SpringGroup2/issues/36) for exact details of update)

**Comment by supiket** [comment]
Implemented planned update.
