### ISSUE TITLE
Creating sequence diagrams for "User participates in discussion" scenario.

### ISSUE THREAD

**Issue by berkaydoner** [bounswe/2021SpringGroup2#40]
I have already completed these diagrams but I forgot to open an issue. -still learning about the issue system.
There should be two sequence diagrams for this scenario. User might comment on a discussion or might answer a comment, which should be separate diagrams as the latter one accesses an additional class.

**Comment by berkaydoner** [comment]
I have added the sequence diagrams:
[Posting a comment on discussion page](https://github.com/bounswe/2021SpringGroup2/wiki/Sequence-Diagrams#posting-a-comment-on-discussion-page)
[Answering a comment on discussion page](https://github.com/bounswe/2021SpringGroup2/wiki/Sequence-Diagrams#answering-a-comment-on-discussion-page)

**Comment by supiket** [comment]
Will add _addAnswer()_  method to user profile and call that method in the diagram, instead of calling comment.answers.add() method.

**Comment by supiket** [comment]
Planned change implemented.
