### ISSUE TITLE
Creating sequence diagram for "User gives a badge to another user" scenario.

### ISSUE THREAD

**Issue by berkaydoner** [bounswe/2021SpringGroup2#41]
This diagram should clearly indicate the relationship between the badge giver user and the badge receiver user, the former will be the actor and the latter will be accessed through classes.

**Comment by berkaydoner** [comment]
I have created the sequence diagram:
[User gives a badge to another user](https://github.com/bounswe/2021SpringGroup2/wiki/Sequence-Diagrams#giving-a-badge-to-another-user)

**Comment by supiket** [comment]
Will add _addBadge(badge)_  method to user profile and call that method in the diagram, instead of calling userProfile.badges(badge) method.

**Comment by supiket** [comment]
Planned change implemented.
