### ISSUE TITLE
Creating sequence diagrams for "User follows/blocks another user" scenarios.

### ISSUE THREAD

**Issue by berkaydoner** [bounswe/2021SpringGroup2#42]
These two scenarios are very similar, so I think it is better to document them in a single issue. The actor will be the follower/blocker user and the followed/blocked user will be accessed through classes.

**Comment by berkaydoner** [comment]
I have created the diagrams:
[User follows a user](https://github.com/bounswe/2021SpringGroup2/wiki/Sequence-Diagrams#following-a-user)
[User blocks a user](https://github.com/bounswe/2021SpringGroup2/wiki/Sequence-Diagrams#blocking-a-user)

**Comment by supiket** [comment]
Registered user lifeline added to diagram.
