### ISSUE TITLE
Create a project plan planning from today until the end of CMPE451

### ISSUE THREAD

**Issue by ege-kaya** [bounswe/2021SpringGroup2#46]
Note down future steps in project implementation from this day on until the end of next semester.
Write down possible dates and time windows for each step.
Report it for addition to the Project Libre chart.

**Comment by berkaydoner** [comment]
I have listed the possible steps for the implementation phase for the backend, frontend and android development. I separated the work into three phases as we will probably have three milestones in CMPE451. 
I also listed some of the predecessor-successor relationships.
