### ISSUE TITLE
Creating Front End for the Practice App

### ISSUE THREAD

**Issue by CenekSanzak** [bounswe/2021SpringGroup2#49]
A simple front end that uses the API implemented in practice app should be created.

**Comment by CenekSanzak** [comment]
I created a react project for the front end. I created a basic structure for navigation among pages.

**Comment by sseff** [comment]
I and @CenekSanzak explained frontend pages in API documentation.

**Comment by supiket** [comment]
I have created

- practice-app/web/src/screens/Equipments.js 
- practice-app/web/src/screens/EquipmentPage.js 
- practice-app/web/src/screens/CreateEquipment.js
- practice-app/web/src/components/EquipmentRow.js
- practice-app/web/src/components/FilterEquipmentModal.js
