### ISSUE TITLE
Necessary Databases

### ISSUE THREAD

**Issue by Voursstrreds** [bounswe/2021SpringGroup2#58]
Databases of users, events and equipments (events and equipments as a post) need to be added.

**Comment by Voursstrreds** [comment]
Database of equipment post is added.

**Comment by ahmetnecipg** [comment]
I have added the database table for "Notification". I created a brand new branch and created a pull request for it. I also requested review and was advised to make some changes by @berkaydoner . I made those changes and committed the new version of my code to the branch I created and I asked for a review again.

**Comment by ege-kaya** [comment]
I created the table for Users using sqlalchemy ORM, requested a review for the necessary fields during a group meeting and was advised to remove the favsports and badges fields. I made the necessary changes and pushed the final version of the User table.

**Comment by berkaydoner** [comment]
I created the post and eventpost tables. Both tables have the columns defined in the class diagram, except the lastUpdateDate and numberOfClicks columns of the post table, which are not necessary for now. Also, latitude and longitude values of the location of the events are added as fields to the eventpost table, which are necessary to [get nearby events](https://github.com/bounswe/2021SpringGroup2/issues/51).  post table is defined as an abstract table, eventpost inherits this table.

**Comment by KeremZaman** [comment]
I fixed some tiny bugs such as missing `@declared_attr` decorators, primary keys. Also, due to the problems of defining foreign keys to abstract classes, I converted `foreign keys using `post.postID` to `eventpost.postID` which will cause equipment posts not to have a comment feature. We can change table design later, but I think it has lower priority. We need to finalize table design asap to proceed in other tasks.

**Comment by CenekSanzak** [comment]
I created tables for Comment and Answer. Comment has foreign keys of post and user tables. Answer has foreign keys of comment and user tables. Both tables have content and datetime. We merged database-tables branch to the development branch and completed this issue.
