### ISSUE TITLE
Create the API method for applying to an event as a player

### ISSUE THREAD

**Issue by ege-kaya** [bounswe/2021SpringGroup2#67]
We need to create an API method for applying to an event as a player. This should work in integration with our database and preferably use a 3rd party API.

**Comment by ege-kaya** [comment]
I created the API method apply_as_player working at the endpoint  `/api/v1.0/events/<int:event_id>/players POST` which takes as input from the request body the ID of the applying user and adds that user to the list of that event's players. I also made its integration with the user and eventpost tables of the database. As a 3rd party API, I used the website randomapi to write my random user generator API. In the case that the applying user's ID does not correspond to a real user in the database, this 3rd party API generates the required fields for that user, who gets added to the database as a new user. Then, this newly generated user is added to the players list of that event.

**Comment by ege-kaya** [comment]
Also, I pushed the changes to the development branch from the player-application branch to adapt to the new separated-files structure of the project

**Comment by KeremZaman** [comment]
I replaced `eventpost` with `Eventpost` and fixed import scheme for dbinit.

**Comment by ege-kaya** [comment]
This function was reviewed and merged to development.
