### ISSUE TITLE
Filling out the group report for Milestone 2

### ISSUE THREAD

**Issue by ege-kaya** [bounswe/2021SpringGroup2#74]
We should urgently start preparing and contributing to our group report to be delivered alongside Milestone 2. Everyone should read and stick to the guidelines provided on Moodle. Please make haste so that we have enough material to potentially present and review during lecture hours on Tuesday.

**Comment by berkaydoner** [comment]
I reviewed the executive summary and the evaluation of tools. I provided descriptions for Flask, PostgreSQL and Postman tools.

**Comment by berkaydoner** [comment]
I wrote my parts for the report. I provided explanations for Geolocation and Geocoding API of Google, filled the personal efforts part. I also helped with copying API documentation to our report and fixed the format.

**Comment by ibrahimbayat** [comment]
In group milestone report, I filled my personal effort part and I explained third party API  ( getPerson) that I used in my function. Also I provided the documentation (parameters, example response, response messages and definition ) of the functions written by me. I contributed the evaluation of tools part that are used in the project.

**Comment by ege-kaya** [comment]
We met at the group meeting yesterday night and went over our group report. Most of it had already been completed. We discussed what was missing and finished it with cooperation, and made our submission. We can now close this issue.
