### ISSUE TITLE
Filling the API Documentation section on the wiki

### ISSUE THREAD

**Issue by ege-kaya** [bounswe/2021SpringGroup2#77]
Everyone should add the documentation of the API endpoints that they have developed to the API Documentation section on our Wiki page, in compliance with the template provided by @CenekSanzak

**Comment by CenekSanzak** [comment]
I created documentation about get spectators function

**Comment by CenekSanzak** [comment]
I created documentation for [getting](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#get-spectator) and [posting](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#post-answer) answers.

**Comment by ahmetnecipg** [comment]
I created the API documentation for [getting equipments](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#get-equipment) and [posting notifications](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#post-notification).

**Comment by sseff** [comment]
I created get_players function documentation [here](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#get-event-by-id).

**Comment by sseff** [comment]
We (@CenekSanzak ) explained frontend tables.

**Comment by sseff** [comment]
I created get_weather function documentation [here](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#get-weather).

**Comment by sseff** [comment]
I created post_user function documentation [here](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#post-user).

**Comment by sseff** [comment]
I created get_notification function [here](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#get-notification).

**Comment by ibrahimbayat** [comment]
I created a documentation [Post spectator](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#post-spectator) and [Get comment ](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#get-comment) for API s written by me. I needed to change the documentation for get comment after the change in design. Before it was taking the parameter  Post_id now it takes  parameter as Event_id. I added an example response value, parameters to call the functions and response messages of the functions. Also I added a simple description of my function for user to understand the functionality of these functions.

**Comment by omerarslnn** [comment]
I created the API documentation for get equipment function [here](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#get-equipment).

**Comment by omerarslnn** [comment]
I created the API documentation for post blocked users [here](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#post-block).

**Comment by omerarslnn** [comment]
I created the API documentation for searching equipment by equipment type and location [here](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#equipment-search)

**Comment by berkaydoner** [comment]
I have written the API documentation for the API's I have created. These methods are as follows:
* [Event Search](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#Get-Events)
* [Post Comment](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#Post-Comment)
* [Get Comment by ID](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#Get-Comment-By-ID)

**Comment by ege-kaya** [comment]
I created the API documentation for my API methods, apply_as_player and get_followers

**Comment by KeremZaman** [comment]
I created the API documentation for the API endpoints that I implemented.

[Get Event by ID](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#Get-Event-by-ID)
[Follow User](https://github.com/bounswe/2021SpringGroup2/wiki/API-Documentation#Follow-User)

**Comment by ege-kaya** [comment]
We made sure yesterday night during the group meeting that everyone has filled their API documentations. I am now closing this issue.
